services:
  grafana:
    networks:
        mon_ids:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:12.1
    ports:
      - "3000:3000"
  alloy:
    image: grafana/alloy:v1.12.0
    networks:
        mon_ids:
    volumes:
      - ./data/suricata/logs/eve.json:/var/log/eve.json
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy
      - ./data/alloy:/var/lib/alloy
    command: ["run", "/etc/alloy/config.alloy"]
  loki:
    image: grafana/loki:3.5.8
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
        mon_ids:
  ####### Prometheus #######
  prometheus:
    user: root
    image: prom/prometheus:v2.48.1
    volumes:
      - ./config/node_exporter/dev/node_exporter.crt:/node_exporter.crt
      - ./data/prometheus:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      mon_ids:
  ####### curl     #######
  curl:
    networks:
      mon_ids:
    build:
      context: ./curl/.
  node_exporter:
    networks:
      mon_ids:
    image: prom/node-exporter:latest
    command: --web.config.file=/etc/node_exporter/config.yml
  ####### Suricata #######
  suricata:
    build:
      context: suricata/.
    network_mode: host
    volumes:
      - ./config/suricata/suricata.yml:/etc/suricata/suricata.yml
      - ./data/suricata/rules:/var/lib/suricata/rules
      - ./data/suricata/logs:/var/log/suricata/
    command: /bin/bash -c "suricata-update && suricata -c /etc/suricata/suricata.yaml -i mon_ids && tail -f /var/log/cron.log"
networks:
  mon_ids:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
    driver_opts:
      com.docker.network.bridge.name: mon_ids

