services:
  grafana:
    networks:
        mon_ids:
    image: grafana/grafana:12.1

  alloy:
    image: grafana/alloy:v1.12.0
    networks:
        mon_ids:
    volumes:
      - ./data/suricata/logs/eve.json:/var/log/eve.json:ro
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy
      - ./data/alloy:/var/lib/alloy
    command: ["run", "/etc/alloy/config.alloy"]
  loki:
    image: grafana/loki:3.5.8
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
        mon_ids:
  ####### Prometheus #######
  prometheus:
    user: root
    image: prom/prometheus:v2.48.1
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      mon_ids:
  ####### curl     #######
  curl:
    networks:
      mon_ids:
    build:
      context: ./curl/.
  node_exporter:
    networks:
      mon_ids:
    image: prom/node-exporter:latest
    command: --web.config.file=/etc/node_exporter/config.yml
  ####### Suricata #######
  suricata:
    build:
      context: suricata/.
    cap_add:
     - NET_ADMIN
     - NET_RAW
    networks:
        mon_ids:
    volumes:
      - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./data/suricata/rules:/var/lib/suricata/rules
      - ./data/suricata/logs:/var/log/suricata/
    command: /bin/bash -c "suricata-update && suricata -c /etc/suricata/suricata.yaml -i eth0 && tail -f /var/log/cron.log"
networks:
  mon_ids:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
    driver_opts:
      com.docker.network.bridge.name: mon_ids

