global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
    scheme: https
    tls_config:
      ca_file: /node_exporter.crt
      insecure_skip_verify: true
    basic_auth:
      username: siem
      password: y]*1hkDE5g|"Em+qzIDE-u2l # fixme should at least be overriden (docker-compose.dev) or use docker secret
