tls_server_config:
  cert_file: /etc/node_exporter/node_exporter.crt
  key_file: /etc/node_exporter/node_exporter.key
basic_auth_users:
  siem: $2y$12$JZzCMaJbJLWkatWmTCy.oOlE2Q4qEUKs5qN791isBWdBSBPrhxl6i

